package com.mmall.model;

import java.util.Date;

public class SysAclModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.id
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.name
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.parent_id
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.level
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.seq
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.status
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.remark
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.operator
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.operate_time
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_acl_module.operate_ip
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.id
     *
     * @return the value of sys_acl_module.id
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.id
     *
     * @param id the value for sys_acl_module.id
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.name
     *
     * @return the value of sys_acl_module.name
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.name
     *
     * @param name the value for sys_acl_module.name
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.parent_id
     *
     * @return the value of sys_acl_module.parent_id
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.parent_id
     *
     * @param parentId the value for sys_acl_module.parent_id
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.level
     *
     * @return the value of sys_acl_module.level
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.level
     *
     * @param level the value for sys_acl_module.level
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.seq
     *
     * @return the value of sys_acl_module.seq
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.seq
     *
     * @param seq the value for sys_acl_module.seq
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.status
     *
     * @return the value of sys_acl_module.status
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.status
     *
     * @param status the value for sys_acl_module.status
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.remark
     *
     * @return the value of sys_acl_module.remark
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.remark
     *
     * @param remark the value for sys_acl_module.remark
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.operator
     *
     * @return the value of sys_acl_module.operator
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.operator
     *
     * @param operator the value for sys_acl_module.operator
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.operate_time
     *
     * @return the value of sys_acl_module.operate_time
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.operate_time
     *
     * @param operateTime the value for sys_acl_module.operate_time
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_acl_module.operate_ip
     *
     * @return the value of sys_acl_module.operate_ip
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_acl_module.operate_ip
     *
     * @param operateIp the value for sys_acl_module.operate_ip
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}