package com.mmall.dao;

import com.mmall.model.SysAcl;

public interface SysAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    int insert(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    int insertSelective(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    SysAcl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    int updateByPrimaryKeySelective(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Thu Mar 24 17:42:12 IRKT 2022
     */
    int updateByPrimaryKey(SysAcl record);
}